<section id="credits_page">
	<h2>Credits</h2>
	<article>
		<h3>Pictures</h3>
		<ul>
			<li><a href="https://www.deviantart.com/noro8/gallery/" target="_blank" rel="noopener">Noro8 / DeviantArt</a></li>
			<li><a href="https://fr.freepik.com/photos-libre/planete-terre-en-danger_945746.htm" target="_blank" rel="noopener">Bedneyimages / Freepik</a></li>
			<li><a href="https://www.deviantart.com/devanndesousa/art/PEACE-84145474" target="_blank" rel="noopener">Devanndesousa / DeviantArt</a></li>
			<li><a href="https://www.deviantart.com/arqsazteckmayan/art/Peace-88419931" target="_blank" rel="noopener">arqsazteckmayan / DeviantArt</a></li>
			<li><a href="https://www.freepik.es/foto-gratis/granja-celulas-solares-estacion-energia-energia-alternativa-sol_2887672.htm" target="_blank" rel="noopener">Jcomp / Freepik</a></li>
			<li><a href="https://www.pexels.com/photo/restaurant-party-architecture-windows-34166/" target="_blank" rel="noopener">Restaurant windows / Pexels</a></li>
			<li><a href="https://www.pexels.com/photo/high-angle-view-of-a-man-256381/" target="_blank" rel="noopener">Technologie / Pexels</a></li>
			<li><a href="https://www.pexels.com/photo/light-london-adverts-piccadilly-circus-34639/" target="_blank" rel="noopener">Advertising / Pexels</a></li>
			<li><a href="https://www.pexels.com/photo/action-america-architecture-avenue-378570/" target="_blank" rel="noopener">Avenue - Pexels</a></li>
			<li><a href="https://pixabay.com/fr/avion-carte-du-monde-terre-global-723900/" target="_blank" rel="noopener">Plane on map / Pixabay</a></li>
			<li><a href="https://www.ladn.eu/city-chaos-virus-epidemic-people-machines-new-york-1080x1920/" target="_blank" rel="noopener">Virus Epidemic / ladn</a></li>
			<li><a href="https://www.deviantart.com/menaria/art/Wasteland-Crossroads-Bar-574081930" target="_blank" rel="noopener">Menaria / DeviantArt</a></li>
			<li><a href="https://pixabay.com/fr/attentat-terroriste-terrorisme-crash-349913/" target="_blank" rel="noopener">Terror crash / Pixabay</a></li>
			<li><a href="https://www.deviantart.com/juavt/art/Swamp-fort-533871270" target="_blank" rel="noopener">Juavt - DeviantArt</a></li>
			<li><a href="https://unsplash.com/photos/2QOqlxjOlPA" target="_blank" rel="noopener">Photo by Alexander Rumpel / Unsplash</a></li>
			<li><a href="https://www.pexels.com/photo/person-s-hands-808960/" target="_blank" rel="noopener">João  Jesus / Pexels</a></li>
			<li><a href="https://www.pexels.com/photo/black-concrete-biulding-51325/" target="_blank" rel="noopener">Building - Pixabay</a></li>
			<li><a href="https://unsplash.com/photos/fqoYO9MjLLQ" target="_blank" rel="noopener">Photo by Andrew Neel / Unsplash</a></li>
			<li><a href="https://www.pexels.com/photo/green-mountains-and-flowing-river-206660/" target="_blank" rel="noopener">Green moutain, flowing river / Pexels</a></li>
			<li><a href="https://www.pexels.com/photo/pineapple-fruit-nature-backpack-47433/" target="_blank" rel="noopener">Photo by Pineapple Supply Co. / Pexels</a></li>
			<li><a href="https://www.pexels.com/photo/photography-of-human-holding-gun-670003/" target="_blank" rel="noopener">Photo by Mike Navolta / Pexels</a></li>
			<li><a href="https://unsplash.com/photos/uY52F3NLPok" target="_blank" rel="noopener">Photo by Fernand De Canne / Unsplash</a></li>
			<li><a href="https://www.deviantart.com/selkys/art/Never-leave-the-trail-625604898" target="_blank" rel="noopener">Selkys / DeviantArt</a></li>				
		</ul>
	</article>
</section>